/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.service;

import com.cribl.openapi.client.ApiException;
import com.cribl.openapi.dto.Error;
import com.cribl.openapi.dto.InlineResponse20031;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConditionsApi
 */
@Ignore
public class ConditionsApiTest {

    private final ConditionsApi api = new ConditionsApi();

    /**
     * Get a list of Condition objects
     *
     * Get a list of Condition objects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void conditionsGetTest() throws ApiException {
        InlineResponse20031 response = api.conditionsGet();

        // TODO: test validations
    }
    /**
     * Get Condition by ID
     *
     * Get Condition by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void conditionsIdGetTest() throws ApiException {
        String id = null;
        InlineResponse20031 response = api.conditionsIdGet(id);

        // TODO: test validations
    }
}
