/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.service;

import com.cribl.openapi.client.ApiException;
import com.cribl.openapi.dto.Error;
import com.cribl.openapi.dto.GlobalVar;
import com.cribl.openapi.dto.InlineResponse20013;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GlobalVariablesApi
 */
@Ignore
public class GlobalVariablesApiTest {

    private final GlobalVariablesApi api = new GlobalVariablesApi();

    /**
     * Get a list of Global Variable objects
     *
     * Get a list of Global Variable objects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void libVarsGetTest() throws ApiException {
        InlineResponse20013 response = api.libVarsGet();

        // TODO: test validations
    }
    /**
     * Delete Global Variable
     *
     * Delete Global Variable
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void libVarsIdDeleteTest() throws ApiException {
        String id = null;
        InlineResponse20013 response = api.libVarsIdDelete(id);

        // TODO: test validations
    }
    /**
     * Get Global Variable by ID
     *
     * Get Global Variable by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void libVarsIdGetTest() throws ApiException {
        String id = null;
        InlineResponse20013 response = api.libVarsIdGet(id);

        // TODO: test validations
    }
    /**
     * Update Global Variable
     *
     * Update Global Variable
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void libVarsIdPatchTest() throws ApiException {
        String id = null;
        GlobalVar body = null;
        InlineResponse20013 response = api.libVarsIdPatch(id, body);

        // TODO: test validations
    }
    /**
     * Create Global Variable
     *
     * Create Global Variable
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void libVarsPostTest() throws ApiException {
        GlobalVar body = null;
        InlineResponse20013 response = api.libVarsPost(body);

        // TODO: test validations
    }
}
