/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.service;

import com.cribl.openapi.client.ApiException;
import com.cribl.openapi.dto.Error;
import com.cribl.openapi.dto.InlineResponse20020;
import com.cribl.openapi.dto.ProfilerItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfilerApi
 */
@Ignore
public class ProfilerApiTest {

    private final ProfilerApi api = new ProfilerApi();

    /**
     * Get a list of ProfilerItem objects
     *
     * Get a list of ProfilerItem objects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemProfilerGetTest() throws ApiException {
        InlineResponse20020 response = api.systemProfilerGet();

        // TODO: test validations
    }
    /**
     * Delete ProfilerItem
     *
     * Delete ProfilerItem
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemProfilerIdDeleteTest() throws ApiException {
        String id = null;
        InlineResponse20020 response = api.systemProfilerIdDelete(id);

        // TODO: test validations
    }
    /**
     * Get ProfilerItem by ID
     *
     * Get ProfilerItem by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemProfilerIdGetTest() throws ApiException {
        String id = null;
        InlineResponse20020 response = api.systemProfilerIdGet(id);

        // TODO: test validations
    }
    /**
     * Update ProfilerItem
     *
     * Update ProfilerItem
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemProfilerIdPatchTest() throws ApiException {
        String id = null;
        ProfilerItem body = null;
        InlineResponse20020 response = api.systemProfilerIdPatch(id, body);

        // TODO: test validations
    }
    /**
     * Create ProfilerItem
     *
     * Create ProfilerItem
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemProfilerPostTest() throws ApiException {
        ProfilerItem body = null;
        InlineResponse20020 response = api.systemProfilerPost(body);

        // TODO: test validations
    }
}
