/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.service;

import com.cribl.openapi.client.ApiException;
import com.cribl.openapi.dto.Error;
import com.cribl.openapi.dto.InlineResponse20023;
import com.cribl.openapi.dto.RestSecret;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretsApi
 */
@Ignore
public class SecretsApiTest {

    private final SecretsApi api = new SecretsApi();

    /**
     * Get a list of RestSecret objects
     *
     * Get a list of RestSecret objects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemSecretsGetTest() throws ApiException {
        InlineResponse20023 response = api.systemSecretsGet();

        // TODO: test validations
    }
    /**
     * Delete RestSecret
     *
     * Delete RestSecret
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemSecretsIdDeleteTest() throws ApiException {
        String id = null;
        InlineResponse20023 response = api.systemSecretsIdDelete(id);

        // TODO: test validations
    }
    /**
     * Get RestSecret by ID
     *
     * Get RestSecret by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemSecretsIdGetTest() throws ApiException {
        String id = null;
        InlineResponse20023 response = api.systemSecretsIdGet(id);

        // TODO: test validations
    }
    /**
     * Update RestSecret
     *
     * Update RestSecret
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemSecretsIdPatchTest() throws ApiException {
        String id = null;
        RestSecret body = null;
        InlineResponse20023 response = api.systemSecretsIdPatch(id, body);

        // TODO: test validations
    }
    /**
     * Create RestSecret
     *
     * Create RestSecret
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemSecretsPostTest() throws ApiException {
        RestSecret body = null;
        InlineResponse20023 response = api.systemSecretsPost(body);

        // TODO: test validations
    }
}
