/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.cribl.openapi.dto.EventBreakerRulesetRules;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * EventBreakerRuleset
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-08T00:23:34.796-04:00[America/New_York]")
public class EventBreakerRuleset {
  @SerializedName("id")
  private String id = null;

  @SerializedName("lib")
  private String lib = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("rules")
  private List<EventBreakerRulesetRules> rules = null;

  public EventBreakerRuleset id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EventBreakerRuleset lib(String lib) {
    this.lib = lib;
    return this;
  }

   /**
   * Get lib
   * @return lib
  **/
  @Schema(description = "")
  public String getLib() {
    return lib;
  }

  public void setLib(String lib) {
    this.lib = lib;
  }

  public EventBreakerRuleset description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Brief description of this ruleset. Optional.
   * @return description
  **/
  @Schema(description = "Brief description of this ruleset. Optional.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EventBreakerRuleset tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * One more tags related to this ruleset. Optional.
   * @return tags
  **/
  @Schema(description = "One more tags related to this ruleset. Optional.")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public EventBreakerRuleset rules(List<EventBreakerRulesetRules> rules) {
    this.rules = rules;
    return this;
  }

  public EventBreakerRuleset addRulesItem(EventBreakerRulesetRules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * List of rules. Evaluated in order, top down.
   * @return rules
  **/
  @Schema(description = "List of rules. Evaluated in order, top down.")
  public List<EventBreakerRulesetRules> getRules() {
    return rules;
  }

  public void setRules(List<EventBreakerRulesetRules> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventBreakerRuleset eventBreakerRuleset = (EventBreakerRuleset) o;
    return Objects.equals(this.id, eventBreakerRuleset.id) &&
        Objects.equals(this.lib, eventBreakerRuleset.lib) &&
        Objects.equals(this.description, eventBreakerRuleset.description) &&
        Objects.equals(this.tags, eventBreakerRuleset.tags) &&
        Objects.equals(this.rules, eventBreakerRuleset.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, lib, description, tags, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventBreakerRuleset {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lib: ").append(toIndentedString(lib)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
