/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * InputStatusSyslogMetrics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-08T00:23:34.796-04:00[America/New_York]")
public class InputStatusSyslogMetrics implements OneOfInputStatusStatusMetrics {
  @SerializedName("name")
  private String name = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("received")
  private BigDecimal received = null;

  @SerializedName("buffered")
  private BigDecimal buffered = null;

  @SerializedName("dropped")
  private BigDecimal dropped = null;

  public InputStatusSyslogMetrics name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InputStatusSyslogMetrics address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public InputStatusSyslogMetrics received(BigDecimal received) {
    this.received = received;
    return this;
  }

   /**
   * Number of messages received
   * @return received
  **/
  @Schema(description = "Number of messages received")
  public BigDecimal getReceived() {
    return received;
  }

  public void setReceived(BigDecimal received) {
    this.received = received;
  }

  public InputStatusSyslogMetrics buffered(BigDecimal buffered) {
    this.buffered = buffered;
    return this;
  }

   /**
   * Number of events in the buffer
   * @return buffered
  **/
  @Schema(description = "Number of events in the buffer")
  public BigDecimal getBuffered() {
    return buffered;
  }

  public void setBuffered(BigDecimal buffered) {
    this.buffered = buffered;
  }

  public InputStatusSyslogMetrics dropped(BigDecimal dropped) {
    this.dropped = dropped;
    return this;
  }

   /**
   * Number of messages dropped (due to max buffer size)
   * @return dropped
  **/
  @Schema(description = "Number of messages dropped (due to max buffer size)")
  public BigDecimal getDropped() {
    return dropped;
  }

  public void setDropped(BigDecimal dropped) {
    this.dropped = dropped;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputStatusSyslogMetrics inputStatusSyslogMetrics = (InputStatusSyslogMetrics) o;
    return Objects.equals(this.name, inputStatusSyslogMetrics.name) &&
        Objects.equals(this.address, inputStatusSyslogMetrics.address) &&
        Objects.equals(this.received, inputStatusSyslogMetrics.received) &&
        Objects.equals(this.buffered, inputStatusSyslogMetrics.buffered) &&
        Objects.equals(this.dropped, inputStatusSyslogMetrics.dropped);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, received, buffered, dropped);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputStatusSyslogMetrics {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    received: ").append(toIndentedString(received)).append("\n");
    sb.append("    buffered: ").append(toIndentedString(buffered)).append("\n");
    sb.append("    dropped: ").append(toIndentedString(dropped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
