/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * License
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-08T00:23:34.796-04:00[America/New_York]")
public class License {
  @SerializedName("email")
  private String email = null;

  @SerializedName("exp")
  private BigDecimal exp = null;

  @SerializedName("f_ph")
  private BigDecimal fPh = null;

  @SerializedName("f_phg")
  private BigDecimal fPhg = null;

  @SerializedName("guid")
  private String guid = null;

  @SerializedName("iat")
  private BigDecimal iat = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("iss")
  private String iss = null;

  @SerializedName("license")
  private String license = null;

  @SerializedName("limits")
  private Map<String, Object> limits = null;

  @SerializedName("quota")
  private BigDecimal quota = null;

  @SerializedName("title")
  private String title = null;

  public License email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public License exp(BigDecimal exp) {
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  @Schema(description = "")
  public BigDecimal getExp() {
    return exp;
  }

  public void setExp(BigDecimal exp) {
    this.exp = exp;
  }

  public License fPh(BigDecimal fPh) {
    this.fPh = fPh;
    return this;
  }

   /**
   * Get fPh
   * @return fPh
  **/
  @Schema(description = "")
  public BigDecimal getFPh() {
    return fPh;
  }

  public void setFPh(BigDecimal fPh) {
    this.fPh = fPh;
  }

  public License fPhg(BigDecimal fPhg) {
    this.fPhg = fPhg;
    return this;
  }

   /**
   * Get fPhg
   * @return fPhg
  **/
  @Schema(description = "")
  public BigDecimal getFPhg() {
    return fPhg;
  }

  public void setFPhg(BigDecimal fPhg) {
    this.fPhg = fPhg;
  }

  public License guid(String guid) {
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @Schema(description = "")
  public String getGuid() {
    return guid;
  }

  public void setGuid(String guid) {
    this.guid = guid;
  }

  public License iat(BigDecimal iat) {
    this.iat = iat;
    return this;
  }

   /**
   * Get iat
   * @return iat
  **/
  @Schema(description = "")
  public BigDecimal getIat() {
    return iat;
  }

  public void setIat(BigDecimal iat) {
    this.iat = iat;
  }

  public License id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public License iss(String iss) {
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  @Schema(description = "")
  public String getIss() {
    return iss;
  }

  public void setIss(String iss) {
    this.iss = iss;
  }

  public License license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @Schema(description = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public License limits(Map<String, Object> limits) {
    this.limits = limits;
    return this;
  }

  public License putLimitsItem(String key, Object limitsItem) {
    if (this.limits == null) {
      this.limits = new HashMap<>();
    }
    this.limits.put(key, limitsItem);
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @Schema(description = "")
  public Map<String, Object> getLimits() {
    return limits;
  }

  public void setLimits(Map<String, Object> limits) {
    this.limits = limits;
  }

  public License quota(BigDecimal quota) {
    this.quota = quota;
    return this;
  }

   /**
   * Get quota
   * @return quota
  **/
  @Schema(description = "")
  public BigDecimal getQuota() {
    return quota;
  }

  public void setQuota(BigDecimal quota) {
    this.quota = quota;
  }

  public License title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    License license = (License) o;
    return Objects.equals(this.email, license.email) &&
        Objects.equals(this.exp, license.exp) &&
        Objects.equals(this.fPh, license.fPh) &&
        Objects.equals(this.fPhg, license.fPhg) &&
        Objects.equals(this.guid, license.guid) &&
        Objects.equals(this.iat, license.iat) &&
        Objects.equals(this.id, license.id) &&
        Objects.equals(this.iss, license.iss) &&
        Objects.equals(this.license, license.license) &&
        Objects.equals(this.limits, license.limits) &&
        Objects.equals(this.quota, license.quota) &&
        Objects.equals(this.title, license.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, exp, fPh, fPhg, guid, iat, id, iss, license, limits, quota, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class License {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    fPh: ").append(toIndentedString(fPh)).append("\n");
    sb.append("    fPhg: ").append(toIndentedString(fPhg)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
