/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.cribl.openapi.dto.PipelineConfGroups;
import com.cribl.openapi.dto.PipelineFunctionConf;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * PipelineConf
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-08T00:23:34.796-04:00[America/New_York]")
public class PipelineConf {
  @SerializedName("asyncFuncTimeout")
  private Integer asyncFuncTimeout = null;

  @SerializedName("output")
  private String output = "default";

  @SerializedName("description")
  private String description = null;

  @SerializedName("functions")
  private List<PipelineFunctionConf> functions = null;

  @SerializedName("groups")
  private Map<String, PipelineConfGroups> groups = null;

  public PipelineConf asyncFuncTimeout(Integer asyncFuncTimeout) {
    this.asyncFuncTimeout = asyncFuncTimeout;
    return this;
  }

   /**
   * Time (in ms) to wait for an async function to complete processing a data item
   * minimum: 0
   * maximum: 10000
   * @return asyncFuncTimeout
  **/
  @Schema(description = "Time (in ms) to wait for an async function to complete processing a data item")
  public Integer getAsyncFuncTimeout() {
    return asyncFuncTimeout;
  }

  public void setAsyncFuncTimeout(Integer asyncFuncTimeout) {
    this.asyncFuncTimeout = asyncFuncTimeout;
  }

  public PipelineConf output(String output) {
    this.output = output;
    return this;
  }

   /**
   * The output destination for events processed by this pipeline
   * @return output
  **/
  @Schema(description = "The output destination for events processed by this pipeline")
  public String getOutput() {
    return output;
  }

  public void setOutput(String output) {
    this.output = output;
  }

  public PipelineConf description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Simple description of this pipeline
   * @return description
  **/
  @Schema(description = "Simple description of this pipeline")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PipelineConf functions(List<PipelineFunctionConf> functions) {
    this.functions = functions;
    return this;
  }

  public PipelineConf addFunctionsItem(PipelineFunctionConf functionsItem) {
    if (this.functions == null) {
      this.functions = new ArrayList<>();
    }
    this.functions.add(functionsItem);
    return this;
  }

   /**
   * List of functions to pass data through
   * @return functions
  **/
  @Schema(description = "List of functions to pass data through")
  public List<PipelineFunctionConf> getFunctions() {
    return functions;
  }

  public void setFunctions(List<PipelineFunctionConf> functions) {
    this.functions = functions;
  }

  public PipelineConf groups(Map<String, PipelineConfGroups> groups) {
    this.groups = groups;
    return this;
  }

  public PipelineConf putGroupsItem(String key, PipelineConfGroups groupsItem) {
    if (this.groups == null) {
      this.groups = new HashMap<>();
    }
    this.groups.put(key, groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @Schema(description = "")
  public Map<String, PipelineConfGroups> getGroups() {
    return groups;
  }

  public void setGroups(Map<String, PipelineConfGroups> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PipelineConf pipelineConf = (PipelineConf) o;
    return Objects.equals(this.asyncFuncTimeout, pipelineConf.asyncFuncTimeout) &&
        Objects.equals(this.output, pipelineConf.output) &&
        Objects.equals(this.description, pipelineConf.description) &&
        Objects.equals(this.functions, pipelineConf.functions) &&
        Objects.equals(this.groups, pipelineConf.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asyncFuncTimeout, output, description, functions, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PipelineConf {\n");
    
    sb.append("    asyncFuncTimeout: ").append(toIndentedString(asyncFuncTimeout)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    functions: ").append(toIndentedString(functions)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
