/*
 * Cribl LogStream
 * REST API Reference of available endpoints and their supported operations for accessing, updating, creating, or deleting resources. Product documentation available at [docs.cribl.io](http://docs.cribl.io).
 *
 * OpenAPI spec version: 3.1.2-abb571bc
 * Contact: support@cribl.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cribl.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SystemSettingsCustomLogo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-08T00:23:34.796-04:00[America/New_York]")
public class SystemSettingsCustomLogo {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("logoDescription")
  private String logoDescription = null;

  @SerializedName("logoImage")
  private String logoImage = null;

  public SystemSettingsCustomLogo enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @Schema(description = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public SystemSettingsCustomLogo logoDescription(String logoDescription) {
    this.logoDescription = logoDescription;
    return this;
  }

   /**
   * Get logoDescription
   * @return logoDescription
  **/
  @Schema(description = "")
  public String getLogoDescription() {
    return logoDescription;
  }

  public void setLogoDescription(String logoDescription) {
    this.logoDescription = logoDescription;
  }

  public SystemSettingsCustomLogo logoImage(String logoImage) {
    this.logoImage = logoImage;
    return this;
  }

   /**
   * Get logoImage
   * @return logoImage
  **/
  @Schema(description = "")
  public String getLogoImage() {
    return logoImage;
  }

  public void setLogoImage(String logoImage) {
    this.logoImage = logoImage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemSettingsCustomLogo systemSettingsCustomLogo = (SystemSettingsCustomLogo) o;
    return Objects.equals(this.enabled, systemSettingsCustomLogo.enabled) &&
        Objects.equals(this.logoDescription, systemSettingsCustomLogo.logoDescription) &&
        Objects.equals(this.logoImage, systemSettingsCustomLogo.logoImage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, logoDescription, logoImage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemSettingsCustomLogo {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    logoDescription: ").append(toIndentedString(logoDescription)).append("\n");
    sb.append("    logoImage: ").append(toIndentedString(logoImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
